/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package santaClaus;

import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author xaronai
 */
public class NorthPall extends javax.swing.JFrame {

    /**
     * Creates new form NorthPall
     */
    boolean firstTime1;
    boolean firstTime2;
    boolean firstTime3;
    boolean firstTime4;
    boolean firstTime5;
    boolean firstTime6;
    boolean firstTime7;
    boolean firstTime8;
    boolean firstTime9;
    boolean firstTime0;
    int firstTime1I;
    int firstTime2I;
    int firstTime3I;
    int firstTime4I;
    int firstTime5I;
    int firstTime6I;
    int firstTime7I;
    int firstTime8I;
    int firstTime9I;
    int firstTime0I;
    public NorthPall() {
        firstTime1=true;
        firstTime2=true;
        firstTime3=true;
        firstTime4=true;
        firstTime5=true;
        firstTime6=true;
        firstTime7=true;
        firstTime8=true;
        firstTime9=true;
        firstTime0=true;
        firstTime1I=0;
        firstTime2I=0;
        firstTime3I=0;
        firstTime4I=0;
        firstTime5I=0;
        firstTime6I=0;
        firstTime7I=0;
        firstTime8I=0;
        firstTime9I=0;
        firstTime0I=0;
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception ex) {}
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        
        jTextArea1.setText("Happenings:");
        
        jLabel1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabel0.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
        jLabelR1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
//                setIcon(~~~~)
//                ImageIcon onoma_eikonas=new ImageIcon(onoma_clasis_project.class.getResource("path"));
//                setIcon(new ImageIcon(path));

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        elvesOnCSB = new javax.swing.JCheckBox();
        raindeersOnCSB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        jLabelR1 = new javax.swing.JLabel();
        jLabelR2 = new javax.swing.JLabel();
        jLabelR3 = new javax.swing.JLabel();
        jLabelR4 = new javax.swing.JLabel();
        jLabelR5 = new javax.swing.JLabel();
        jLabelR6 = new javax.swing.JLabel();
        jLabelR7 = new javax.swing.JLabel();
        jLabelR8 = new javax.swing.JLabel();
        jLabelR9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 232, 230));

        elvesOnCSB.setText("Elves on CS");

        raindeersOnCSB.setText("Raindeers on CS");

        jLabel1.setText("1");
        jLabel1.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel1.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel1.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel2.setText("2");
        jLabel2.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel2.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel2.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel3.setText("3");
        jLabel3.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel3.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel3.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel4.setText("4");
        jLabel4.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel4.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel4.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel5.setText("5");
        jLabel5.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel5.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel5.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel6.setText("6");
        jLabel6.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel6.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel6.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel7.setText("7");
        jLabel7.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel7.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel7.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel8.setText("8");
        jLabel8.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel8.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel8.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel9.setText("9");
        jLabel9.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel9.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel9.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabel0.setText("10");
        jLabel0.setMaximumSize(new java.awt.Dimension(44, 44));
        jLabel0.setMinimumSize(new java.awt.Dimension(44, 44));
        jLabel0.setPreferredSize(new java.awt.Dimension(44, 44));

        jLabelR1.setText("1");
        jLabelR1.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR1.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR1.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR2.setText("2");
        jLabelR2.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR2.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR2.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR3.setText("3");
        jLabelR3.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR3.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR3.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR4.setText("4");
        jLabelR4.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR4.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR4.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR5.setText("5");
        jLabelR5.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR5.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR5.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR6.setText("6");
        jLabelR6.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR6.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR6.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR7.setText("7");
        jLabelR7.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR7.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR7.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR8.setText("8");
        jLabelR8.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR8.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR8.setPreferredSize(new java.awt.Dimension(45, 45));

        jLabelR9.setText("9");
        jLabelR9.setMaximumSize(new java.awt.Dimension(45, 45));
        jLabelR9.setMinimumSize(new java.awt.Dimension(45, 45));
        jLabelR9.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(elvesOnCSB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(raindeersOnCSB)))
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelR2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelR4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelR5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelR7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelR8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabelR9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elvesOnCSB)
                    .addComponent(raindeersOnCSB))
                .addGap(10, 10, 10))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Not working yet");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("Symbols");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Symbols2 temp = new Symbols2();
        temp.setLocationRelativeTo(null);
        temp.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText("Happenings:");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NorthPall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NorthPall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NorthPall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NorthPall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NorthPall().setVisible(true);
            }
        });
    }
    
    public void jTextArea1TextChanger(String newText) {
        jTextArea1.append("\n"+newText);
    }
    
    public void presserElve(int id){
        switch (id) {
            case 1: if(firstTime1I == 0){
                        jLabel1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime1I++;
                    } else if (firstTime1I == 1) {
                        jLabel1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime1I++;
                    } else if (firstTime1I == 2) {
                        jLabel1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime1I++;
                    } else {
                        jLabel1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime1I = 0;
                    }
                    break;
            case 2: if(firstTime2I == 0){
                        jLabel2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime2I++;
                    } else if (firstTime2I == 1) {
                        jLabel2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime2I++;
                    } else if (firstTime2I == 2) {
                        jLabel2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime2I++;
                    } else {
                        jLabel2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime2I = 0;
                    }
                    break;
            case 3: if(firstTime3I == 0){
                        jLabel3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime3I++;
                    } else if (firstTime3I == 1) {
                        jLabel3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime3I++;
                    } else if (firstTime3I == 2) {
                        jLabel3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime3I++;
                    } else {
                        jLabel3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime3I = 0;
                    }
                    break;
            case 4: if(firstTime4I == 0){
                        jLabel4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime4I++;
                    } else if (firstTime4I == 1) {
                        jLabel4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime4I++;
                    } else if (firstTime4I == 2) {
                        jLabel4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime4I++;
                    } else {
                        jLabel4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime4I = 0;
                    }
                    break;
            case 5: if(firstTime5I == 0){
                        jLabel5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime5I++;
                    } else if (firstTime5I == 1) {
                        jLabel5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime5I++;
                    } else if (firstTime5I == 2) {
                        jLabel5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime5I++;
                    } else {
                        jLabel5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime5I = 0;
                    }
                    break;
            case 6: if(firstTime6I == 0){
                        jLabel6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime6I++;
                    } else if (firstTime6I == 1) {
                        jLabel6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime6I++;
                    } else if (firstTime6I == 2) {
                        jLabel6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime6I++;
                    } else {
                        jLabel6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime6I = 0;
                    }
                    break;
            case 7: if(firstTime7I == 0){
                        jLabel7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime7I++;
                    } else if (firstTime7I == 1) {
                        jLabel7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime7I++;
                    } else if (firstTime7I == 2) {
                        jLabel7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime7I++;
                    } else {
                        jLabel7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime7I = 0;
                    }
                    break;
            case 8: if(firstTime8I == 0){
                        jLabel8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime8I++;
                    } else if (firstTime8I == 1) {
                        jLabel8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime8I++;
                    } else if (firstTime8I == 2) {
                        jLabel8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime8I++;
                    } else {
                        jLabel8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime8I = 0;
                    }
                    break;
            case 9: if(firstTime9I == 0){
                        jLabel9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime9I++;
                    } else if (firstTime9I == 1) {
                        jLabel9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime9I++;
                    } else if (firstTime9I == 2) {
                        jLabel9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime9I++;
                    } else {
                        jLabel9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime9I = 0;
                    }
                    break;
            case 0: if(firstTime0I == 0){
                        jLabel0.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2d.gif")));
                        firstTime0I++;
                    } else if (firstTime0I == 1) {
                        jLabel0.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2e.gif")));
                        firstTime0I++;
                    } else if (firstTime0I == 2) {
                        jLabel0.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2f.png")));
                        firstTime0I++;
                    } else {
                        jLabel0.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled2a.png")));
                        firstTime0I = 0;
                    }
                    break;
            default:break;
        }
//        jPanel1.revalidate();
//        jPanel1.repaint();
    }
    public void presserReindeerAll(){
        jLabelR1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
        jLabelR9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4a.png")));
    }
    public void presserReindeer(int id){
        switch (id) {
            case 1: if(firstTime1) {
                        jLabelR1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime1 = false;
                    } else {
                        jLabelR1.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime1 = true;
                    }
                    break;
            case 2: if(firstTime2) {
                        jLabelR2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime2 = false;
                    } else {
                        jLabelR2.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime2 = true;
                    }
                    break;
            case 3: if(firstTime3) {
                        jLabelR3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime3 = false;
                    } else {
                        jLabelR3.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime3 = true;
                    }
                    break;
            case 4: if(firstTime4) {
                        jLabelR4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime4 = false;
                    } else {
                        jLabelR4.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime4 = true;
                    }
                    break;
            case 5: if(firstTime5) {
                        jLabelR5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime5 = false;
                    } else {
                        jLabelR5.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime5 = true;
                    }
                    break;
            case 6: if(firstTime6) {
                        jLabelR6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime6 = false;
                    } else {
                        jLabelR6.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime6 = true;
                    }
                    break;
            case 7: if(firstTime7) {
                        jLabelR7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime7 = false;
                    } else {
                        jLabelR7.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime7 = true;
                    }
                    break;
            case 8: if(firstTime8) {
                        jLabelR8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime8 = false;
                    } else {
                        jLabelR8.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime8 = true;
                    }
                    break;
            case 0: if(firstTime9) {
                        jLabelR9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4c.gif")));
                        firstTime9 = false;
                    } else {
                        jLabelR9.setIcon(new ImageIcon(NorthPall.class.getResource("/images/Untitled4d.png")));
                        firstTime9 = true;
                    }
                    break;
        }
//        jPanel1.revalidate();
//        jPanel1.repaint();
    }
//    public void presserReindeer(int id){
//        switch (id) {
//            case 1:  reinNo1B.doClick();
//                     break;
//            case 2:  reinNo2B.doClick();
//                     break;
//            case 3:  reinNo3B.doClick();
//                     break;
//            case 4:  reinNo4B.doClick();
//                     break;
//            case 5:  reinNo5B.doClick();
//                     break;
//            case 6:  reinNo6B.doClick();
//                     break;
//            case 7:  reinNo7B.doClick();
//                     break;
//            case 8:  reinNo8B.doClick();
//                     break;
//            case 0:  reinNo9B.doClick();
//                     break;
//        }
//        jPanel1.revalidate();
//        jPanel1.repaint();
//    }
    
    public void presserElvesOnCSB(){
        elvesOnCSB.doClick();
    }
    public void presserRaindeersOnCSB(){
        raindeersOnCSB.doClick();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox elvesOnCSB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelR1;
    private javax.swing.JLabel jLabelR2;
    private javax.swing.JLabel jLabelR3;
    private javax.swing.JLabel jLabelR4;
    private javax.swing.JLabel jLabelR5;
    private javax.swing.JLabel jLabelR6;
    private javax.swing.JLabel jLabelR7;
    private javax.swing.JLabel jLabelR8;
    private javax.swing.JLabel jLabelR9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox raindeersOnCSB;
    // End of variables declaration//GEN-END:variables
}
